In [1]:
import pandas as pd
import numpy as np

In [2]:
#List of CSV file to combined
csv_files = [
    #Thoi trang
    'quanaollms.csv',
    'giaydepllms.csv',
    'Data_Jewelry_After_LLMs.csv',

    #Dien tu
    'LLM_DienThoai.csv',
    'Data_Laptop_After_LLMs.csv',
    'LLM_Tivi.csv'
]

#Read and combine CSV files into a DataFrame
data_final = pd.concat([pd.read_csv(file) for file in csv_files])
#Reset index
data_final.reset_index(drop=True, inplace=True)
data_final.index = np.arange(1, len(data_final)+1)


#Convert to "DienThoai.csv" file
data_final.to_csv("Final_Data_LLM.csv", index=False)

In [3]:
data_final

,Type,Price_sale,Sale_off,Total_sold,Preview,Location,Price_original,Ship_price,Sale_rating,Ship_on_time,Chat_response,One_star,Two_star,Three_star,Four_star,Five_star
1,quần áo,35891,64.0,3000.0,1022.0,Hồ Chí Minh,100000.0,16500.0,97.0,100.0,100.0,20.0,7.0,27.0,36.0,932.0
2,quần áo,25000,50.0,907.0,241.0,Hồ Chí Minh,71998.0,16500.0,91.0,100.0,50.0,5.0,2.0,6.0,7.0,222.0
3,quần áo,79000,43.0,961.0,260.0,Hà Nội,139000.0,32700.0,92.0,99.0,33.0,11.0,8.0,8.0,16.0,218.0
4,quần áo,36000,60.0,102.0,21.0,Nam Định,189000.0,37700.0,94.0,100.0,83.0,1.0,0.0,1.0,1.0,18.0
5,quần áo,15971,54.0,219.0,68.0,Hà Nội,59000.0,32700.0,95.0,100.0,100.0,0.0,1.0,0.0,3.0,65.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7196,tivi,5390000,34.0,9.0,Ho Chi Minh,5590000,0.0,96.0,100,100.0,2.0,0.0,0.0,0.0,7.0,NaN
7197,tivi,2730000,NaN,NaN,NaN,Ho Chi Minh,NaN,38000.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0
7198,tivi,6150000,NaN,NaN,NaN,Ho Chi Minh,9990000.0,NaN,97,98.0,89.0,0.0,0.0,0.0,0.0,0.0
7199,tivi,4250000,NaN,NaN,NaN,Ha Noi,4990000.0,135500.0,100,40.0,NaN,0.0,0.0,0.0,0.0,0.0
7200,tivi,2650000,NaN,NaN,NaN,Ho Chi Minh,NaN,45100.0,100,NaN,50.0,0.0,0.0,0.0,0.0,0.0