In [13]:
import os
import requests
import pandas as pd
import unidecode
from tqdm import tqdm

In [14]:
name_input = "quanao.csv"
name_output = "quanaollms.csv"

In [15]:
data = pd.read_csv(name_input)
data.head(10)

,Type,Price_sale,Sale_off,Total_sold,Preview,Location,Price_original,Ship_price,Sale_rating,Ship_on_time,Chat_response,One_star,Two_star,Three_star,Four_star,Five_star
0,quần áo,35.891 ₫,64% Off,3.0K Đã bán,(1022),Hồ Chí Minh,100.000 ₫,16.500 ₫,97%,100%,100%,20.0,7.0,27.0,36.0,932.0
1,quần áo,25.000 ₫,50% Off,907 Đã bán,(241),Hồ Chí Minh,71.998 ₫,16.500 ₫,91%,100%,50%,5.0,2.0,6.0,7.0,222.0
2,quần áo,79.000 ₫,43% Off,961 Đã bán,(260),Hà Nội,139.000 ₫,32.700 ₫,92%,99%,33%,11.0,8.0,8.0,16.0,218.0
3,quần áo,36.000 ₫,60% Off,102 Đã bán,(21),Nam Định,189.000 ₫,37.700 ₫,94%,100%,83%,1.0,0.0,1.0,1.0,18.0
4,quần áo,15.971 ₫,54% Off,219 Đã bán,(68),Hà Nội,59.000 ₫,32.700 ₫,95%,100%,100%,0.0,1.0,0.0,3.0,65.0
5,quần áo,59.000 ₫,67% Off,3.8K Đã bán,(1147),Hồ Chí Minh,179.000 ₫,16.500 ₫,97%,96%,97%,7.0,5.0,18.0,32.0,1085.0
6,quần áo,45.000 ₫,NaN,116 Đã bán,(27),Hồ Chí Minh,NaN,18.300 ₫,92%,99%,60%,0.0,0.0,2.0,2.0,23.0
7,quần áo,50.000 ₫,61% Off,14.6K Đã bán,(3067),Hồ Chí Minh,129.000 ₫,16.500 ₫,97%,96%,97%,64.0,23.0,70.0,111.0,2799.0
8,quần áo,33.454 ₫,66% Off,6.0K Đã bán,(1725),Hồ Chí Minh,99.000 ₫,16.500 ₫,97%,96%,97%,20.0,17.0,28.0,44.0,1616.0
9,quần áo,149.000 ₫,NaN,5 Đã bán,NaN,Hồ Chí Minh,NaN,18.300 ₫,92%,99%,60%,0.0,0.0,0.0,0.0,0.0

In [16]:
s = requests.Session()

api_base = "https://api.endpoints.anyscale.com/v1"
# Replace with long-lived credentials for production
token = "esecret_exa36aaw8u5pqdsppk8dqxi5ij"
url = f"{api_base}/chat/completions"

In [17]:
def call_api(formatted_data):
    body = {
    "model": "meta-llama/Meta-Llama-3-70B-Instruct",
    "messages": [
        {
        "role": "user",
        "content": "bạn là trợ lý ảo về AI và có nhiệm vụ chính là chuẩn hoá data một cách chính xác nhất"
        },
        {
        "role": "assistant",
        "content": "Nice to meet you! As a virtual assistant specializing in AI, my primary task is to ensure data standardization with utmost accuracy. I'm here to help you with data preprocessing, data cleaning, and data transformation to make your data reliable, consistent, and ready for analysis or modeling.\n\nTo achieve this, I'll employ various techniques, including:\n\n1. **Data Profiling**: I'll analyze your data to identify patterns, outliers, and inconsistencies, providing insights into data quality and potential issues.\n2. **Data Cleaning**: I'll correct errors, handle missing values, and remove duplicates to ensure data integrity and consistency.\n3. **Data Transformation**: I'll convert data types, perform aggregations, and apply business rules to transform your data into a standardized format.\n4. **Data Validation**: I'll check your data against a set of rules, constraints, and formats to ensure it meets the required standards.\n5. **Data Normalization**: I'll organize your data into a structured format, making it easier to analyze and model.\n\nMy expertise includes working with various data formats, such as CSV, JSON, XML, and databases like MySQL, PostgreSQL, and MongoDB. I'm also familiar with data standardization frameworks like ISO 11179 and Dublin Core.\n\nPlease provide me with more information about your data, such as:\n\n* What type of data do you have (e.g., customer information, transactional data, sensor readings)?\n* What is the current format of your data (e.g., CSV, JSON, database)?\n* What are the specific data quality issues you're experiencing (e.g., missing values, duplicates, inconsistencies)?\n* Are there any specific data standards or regulations you need to comply with (e.g., GDPR, HIPAA)?\n\nThe more information you provide, the better I can assist you in standardizing your data with accuracy and efficiency."
        },
        {
        "role": "user",
        "content": "Mỗi mục dữ liệu được ngăn cách bởi dấu |. Không bỏ bất kì 1 mục nào, không thêm bất kỳ mục nào, hãy chuẩn hóa thông tin về dạng số tương ứng, địa điểm giữ nguyên, nếu là giá trị None thì ghi là None. Ngăn cách các giá trị bằng dấu phẩy, không cần giải thích output, output bạn trả ra cho tôi có đúng 16 cột nhé: quần áo|35.891 ₫|64% Off|3.0K Đã bán|(1022)|Hồ Chí Minh|100.000 ₫|16.500 ₫|97%|100%|100%|20.0|7.0|27.0|36.0|932.0"
        },
        {
        "role": "assistant",
        "content": "Here is the standardized data with 16 columns, separated by commas:\n\nQuần áo,35891,64,3000,1022,Hồ Chí Minh,100000,16500,97,100,100,20,7,27,36,932"
        },
        {
        "role": "user",
        "content": "không viết hoa chữ đầu bạn phải trả về là: Here is the standardized output:\n\nquần áo,35891,64,3000,1022,Hồ Chí Minh,100000,16500,97,100,100,20,7,27,36,932"
        },
        {
        "role": "assistant",
        "content": "Here is the standardized output:\n\nquần áo,35891,64,3000,1022,Hồ Chí Minh,100000,16500,97,100,100,20,7,27,36,932"
        },
        {
        "role": "user",
        "content": f"{formatted_data}"
        }
    ],
    "temperature": 0,
    "max_tokens": 512,
    "top_p": 1,
    "frequency_penalty": 0
    }

    response = s.post(url, headers={"Authorization": f"Bearer {token}"}, json=body)
    return response.json()

In [18]:
total_error = 0
def format_row(row):
    return '|'.join(map(str, row.values))

results = []
for index, row in tqdm(data.iterrows(), total=data.shape[0], desc="Processing rows"):
    formatted_data = format_row(row)
    api_response = call_api(formatted_data)
    
    if 'choices' in api_response and api_response['choices']:
        cleaned_data = api_response['choices'][0]['message']['content'].strip()
        cleaned_data = cleaned_data.replace('Here is the standardized output:\n\n', '')
        # Kiểm tra điều kiện đủ 16 cột hay không
        count_commas = cleaned_data.count(',')
        if (count_commas == 15):
            results.append(cleaned_data.split(','))
        else:   # Nếu không đủ thì bỏ sang hàng tiếp theo
            print(f"Error at {index}")
            total_error += 1
            continue
    else:
        print(f"No choices found for row {index}")
        break

Processing rows: 100%|██████████| 1200/1200 [55:12<00:00,  2.76s/it]

In [19]:
print(total_error)

0

In [20]:
cleaned_df = pd.DataFrame(results, columns=data.columns)
cleaned_df

,Type,Price_sale,Sale_off,Total_sold,Preview,Location,Price_original,Ship_price,Sale_rating,Ship_on_time,Chat_response,One_star,Two_star,Three_star,Four_star,Five_star
0,quần áo,35891,64,3000,1022,Hồ Chí Minh,100000,16500,97,100,100,20,7,27,36,932
1,quần áo,25000,50,907,241,Hồ Chí Minh,71998,16500,91,100,50,5,2,6,7,222
2,quần áo,79000,43,961,260,Hà Nội,139000,32700,92,99,33,11,8,8,16,218
3,quần áo,36000,60,102,21,Nam Định,189000,37700,94,100,83,1,0,1,1,18
4,quần áo,15971,54,219,68,Hà Nội,59000,32700,95,100,100,0,1,0,3,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,quần áo,53258,47,1500,281,Hồ Chí Minh,100000,16500,94,85,100,26,15,4,5,232
1196,quần áo,71000,75,2600,810,Hà Nội,285000,32700,76,100,100,105,17,18,37,633
1197,quần áo,32845,66,13,4,Hà Nội,98000,38000,68,100,82,1,0,0,0,3
1198,quần áo,69000,54,10,5,Hồ Chí Minh,200000,16500,88,99,100,0,0,0,0,0
1199,quần áo,19369,88,2400,440,Hồ Chí Minh,159000,16500,92,98,100,0,0,0,0,0

In [21]:
cleaned_df.to_csv(name_output, index=False)