In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("Data_Laptop.csv")
data.head()

,Type,Title,Link,Price_sale,Sale_off,Total_sold,Preview,Location,Price_original,Ship_price,Return,Sale_rating,Ship_on_time,Chat_response,One_star,Two_star,Three_star,Four_star,Five_star
0,laptop,[6.6 SALE TO] MacBook Air 2020 13.3 inches M1-...,https://www.lazada.vn/products/66-sale-to-macb...,17.990.000 ₫,38% Off,3.0K Đã bán,(666),Hồ Chí Minh,28.990.000 ₫,10.200 ₫,30 Ngày Trả Hàng Miễn Phí,94%,98%,100%,['28'],['5'],['10'],['17'],['606']
1,laptop,"Lenovo mới tinh core Intel i7 6560U laptop 15,...",https://www.lazada.vn/products/lenovo-moi-tinh...,7.223.999 ₫,"52% Off\nLazFlash Sale,kết thúc sau 9h",51 Đã bán,(5),Hải Phòng,13.899.999 ₫,Miễn phí,NaN,100%,100%,80%,['0'],['0'],['0'],['0'],['5']
2,laptop,"Máy Tính Xách Tay Bàn Phím Bao Gồm, Màng Bảo V...",https://www.lazada.vn/products/may-tinh-xach-t...,39.000 ₫,17% Off,312 Đã bán,(67),Hồ Chí Minh,47.000 ₫,17.000 ₫,NaN,96%,98%,90%,['11'],['1'],['3'],['5'],['47']
3,laptop,ASUS máy tính xách tay mới tinh Intel core i7 ...,https://www.lazada.vn/products/asus-may-tinh-x...,7.254.959 ₫,45% Off,16 Đã bán,(3),Hải Phòng,13.199.999 ₫,Miễn phí,NaN,100%,100%,80%,['0'],['0'],['0'],['0'],['3']
4,laptop,LaptopLENOVO THINKPAD X1 Carbon Gen 7 X1 Carbo...,https://www.lazada.vn/products/laptoplenovo-th...,4.390.000 ₫,"20% Off\nLazFlash Sale,kết thúc sau 9h",126 Đã bán,(29),Hà Nội,5.900.000 ₫,Miễn phí,NaN,98%,100%,100%,['0'],['0'],['1'],['0'],['28']

In [3]:
#Check missing value
data.isnull().sum().sort_values(ascending=False)

Return            1008
Total_sold         539
Price_original     536
Sale_off           509
Preview            466
Ship_price          51
Chat_response       13
Sale_rating         13
Ship_on_time        13
Four_star            0
Three_star           0
Two_star             0
One_star             0
Type                 0
Title                0
Location             0
Price_sale           0
Link                 0
Five_star            0
dtype: int64

In [4]:
#Drop Title, Link, Return
new_data = data.drop(columns=['Title', 'Link', 'Return'], axis=1)
new_data.head()

,Type,Price_sale,Sale_off,Total_sold,Preview,Location,Price_original,Ship_price,Sale_rating,Ship_on_time,Chat_response,One_star,Two_star,Three_star,Four_star,Five_star
0,laptop,17.990.000 ₫,38% Off,3.0K Đã bán,(666),Hồ Chí Minh,28.990.000 ₫,10.200 ₫,94%,98%,100%,['28'],['5'],['10'],['17'],['606']
1,laptop,7.223.999 ₫,"52% Off\nLazFlash Sale,kết thúc sau 9h",51 Đã bán,(5),Hải Phòng,13.899.999 ₫,Miễn phí,100%,100%,80%,['0'],['0'],['0'],['0'],['5']
2,laptop,39.000 ₫,17% Off,312 Đã bán,(67),Hồ Chí Minh,47.000 ₫,17.000 ₫,96%,98%,90%,['11'],['1'],['3'],['5'],['47']
3,laptop,7.254.959 ₫,45% Off,16 Đã bán,(3),Hải Phòng,13.199.999 ₫,Miễn phí,100%,100%,80%,['0'],['0'],['0'],['0'],['3']
4,laptop,4.390.000 ₫,"20% Off\nLazFlash Sale,kết thúc sau 9h",126 Đã bán,(29),Hà Nội,5.900.000 ₫,Miễn phí,98%,100%,100%,['0'],['0'],['1'],['0'],['28']

In [5]:
#Display the unique values of columns: Sale_rating, Ship_on_time, và Chat_response
unique_sale_rating = new_data['Sale_rating'].unique()
unique_ship_on_time = new_data['Ship_on_time'].unique()
unique_chat_response = new_data['Chat_response'].unique()

print(unique_sale_rating, "\n")
print(unique_ship_on_time, "\n")
print(unique_chat_response, "\n")

['94%' '100%' '96%' '98%' 'Không đủ thông tin' '87%' '97%' '92%' '91%'
 '99%' '79%' '88%' '86%' '82%' '95%' nan '93%' '90%' 'Nhà bán hàng mới'
 '85%' '84%' '67%']

['98%' '100%' 'Không đủ thông tin' '20%' '37%' '66%' '91%' '75%' '50%'
 '86%' '85%' '99%' '81%' nan '80%' '65%' '77%' '92%' '67%' '71%' '97%'
 '84%' '28%' '93%' '33%' '83%' '94%' '82%' '95%' '90%']

['100%' '80%' '90%' 'Không đủ thông tin' '76%' '83%' '85%' '92%' '66%'
 '95%' '88%' nan '94%' '93%' '75%' '96%' '78%' '71%' '33%' '99%' '98%'
 '87%' '97%' '50%' '91%' '82%' '89%' '81%' '86%' '77%' '40%' '37%']

In [6]:
new_data['Sale_rating'].replace(['Nhà bán hàng mới', 'Không đủ thông tin'], np.nan, inplace=True)
new_data['Ship_on_time'].replace(['Không đủ thông tin'], np.nan, inplace=True)
new_data['Chat_response'].replace(['Không đủ thông tin'], np.nan, inplace=True)

In [7]:
#Check columns: Sale_rating, Ship_on_time, và Chat_response
unique_sale_rating = new_data['Sale_rating'].unique()
unique_ship_on_time = new_data['Ship_on_time'].unique()
unique_chat_response = new_data['Chat_response'].unique()

print(unique_sale_rating, "\n")
print(unique_ship_on_time, "\n")
print(unique_chat_response, "\n")

['94%' '100%' '96%' '98%' nan '87%' '97%' '92%' '91%' '99%' '79%' '88%'
 '86%' '82%' '95%' '93%' '90%' '85%' '84%' '67%']

['98%' '100%' nan '20%' '37%' '66%' '91%' '75%' '50%' '86%' '85%' '99%'
 '81%' '80%' '65%' '77%' '92%' '67%' '71%' '97%' '84%' '28%' '93%' '33%'
 '83%' '94%' '82%' '95%' '90%']

['100%' '80%' '90%' nan '76%' '83%' '85%' '92%' '66%' '95%' '88%' '94%'
 '93%' '75%' '96%' '78%' '71%' '33%' '99%' '98%' '87%' '97%' '50%' '91%'
 '82%' '89%' '81%' '86%' '77%' '40%' '37%']

In [8]:
# Hàm để loại bỏ ký tự không mong muốn và lấy giá trị bên trong
def extract_number(val):
    if isinstance(val, str):
        return val.strip("[]'")  # loại bỏ các ký tự không mong muốn
    return val

# Áp dụng hàm extract_number cho từng cột
for column in new_data.columns[11:16]:
    new_data[column] = new_data[column].apply(extract_number)

In [9]:
new_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Type            1200 non-null   object
 1   Price_sale      1200 non-null   object
 2   Sale_off        691 non-null    object
 3   Total_sold      661 non-null    object
 4   Preview         734 non-null    object
 5   Location        1200 non-null   object
 6   Price_original  664 non-null    object
 7   Ship_price      1149 non-null   object
 8   Sale_rating     1111 non-null   object
 9   Ship_on_time    967 non-null    object
 10  Chat_response   951 non-null    object
 11  One_star        1200 non-null   object
 12  Two_star        1200 non-null   object
 13  Three_star      1200 non-null   object
 14  Four_star       1200 non-null   object
 15  Five_star       1200 non-null   object
dtypes: object(16)
memory usage: 150.1+ KB

In [11]:
new_data.to_csv("Preprocessing_Data_Laptop.csv", index=False)